/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'secondary-fixed-dim': '#bcc3ff',
        'tertiary-fixed-dim': '#b1cad7',
        background: '#fcf9f8',
        'outline-variant': '#c5c9ac',
        primary: '#536600',
        'primary-container': '#d4ff00',
        'on-secondary-fixed': '#0b144f',
        'on-surface-variant': '#444932',
        'on-surface': '#1c1b1b',
        outline: '#757a60',
        'on-primary-fixed': '#171e00',
        'surface-container-highest': '#e5e2e1',
        'secondary-fixed': '#dfe0ff',
        tertiary: '#4a626d',
        'surface-tint': '#536600',
        'inverse-primary': '#b0d500',
        'on-secondary-container': '#404883',
        'on-background': '#1c1b1b',
        'on-secondary': '#ffffff',
        'surface-container': '#f0edec',
        'on-tertiary-fixed-variant': '#324a54',
        'tertiary-fixed': '#cde7f3',
        'primary-fixed-dim': '#b0d500',
        'on-primary-fixed-variant': '#3e4c00',
        'on-primary': '#ffffff',
        error: '#ba1a1a',
        'on-tertiary': '#ffffff',
        'on-secondary-fixed-variant': '#3a427c',
        'surface-variant': '#e5e2e1',
        'tertiary-container': '#d8f2ff',
        'on-tertiary-container': '#576f7a',
        'error-container': '#ffdad6',
        'surface-container-low': '#f6f3f2',
        surface: '#fcf9f8',
        'on-error': '#ffffff',
        secondary: '#525a96',
        'on-tertiary-fixed': '#041e28',
        'surface-bright': '#fcf9f8',
        'inverse-surface': '#313030',
        'primary-fixed': '#caf300',
        'inverse-on-surface': '#f3f0ef',
        'on-error-container': '#93000a',
        'surface-dim': '#dcd9d9',
        'surface-container-high': '#ebe7e7',
        'on-primary-container': '#5f7400',
        'surface-container-lowest': '#ffffff',
        'secondary-container': '#b2bafd',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        unit: '4px',
        gutter: '24px',
        'margin-desktop': '64px',
        'margin-mobile': '20px',
        'container-max': '1440px',
      },
      maxWidth: {
        'container-max': '1440px',
      },
      fontFamily: {
        'body-md': ['Inter', 'sans-serif'],
        'button-text': ['"Plus Jakarta Sans"', 'sans-serif'],
        'technical-label': ['"JetBrains Mono"', 'monospace'],
        'headline-lg-mobile': ['"Plus Jakarta Sans"', 'sans-serif'],
        'headline-lg': ['"Plus Jakarta Sans"', 'sans-serif'],
        'headline-xl': ['"Plus Jakarta Sans"', 'sans-serif'],
      },
      fontSize: {
        'body-md': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
        'button-text': ['14px', { lineHeight: '1', fontWeight: '600' }],
        'technical-label': [
          '12px',
          { lineHeight: '1.2', letterSpacing: '0.05em', fontWeight: '500' },
        ],
        'headline-lg-mobile': ['28px', { lineHeight: '1.2', fontWeight: '600' }],
        'headline-lg': ['32px', { lineHeight: '1.2', fontWeight: '600' }],
        'headline-xl': [
          '48px',
          { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '700' },
        ],
      },
    },
  },
  plugins: [],
}
